### ISSUE TITLE
RowUpdating e.NewVaules is an empty string

### ISSUE THREAD

**Issue by ToddEvansHome** [DevExpress-Examples/out-of-maintenance-how-to-implement-a-checkcombobox-editor-in-the-aspxgridview-e2250#1]
Upon clicking the Update link, on the server side RowUpdating event, the ASPxDataUpdatingEventArgs e.NewValues is an empty string.

**Comment by zabelin-vladimir** [comment]
Please, submit a corresponding ticket for this issue using our Support Center (this is our official support channel) rather than GitHub:
https://www.devexpress.com/Support/Center/Question/Create 
 
This way we can process your request in the most efficient way.
 
If you do not have a DevExpress account, please register on our website to get access to the Support Center:
https://www.devexpress.com/MyAccount/Register/
